spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false #수정 내용이 바로 반영되도록 캐시 비활성 (운영에서는 true)
    check-template-location: false
    mode: HTML

# JWT properties
jwt:
  key: jawsProjectMadeBySeungHoAndKyungHyun
  issuer: jaws
  accessTokenExpiration: 60000
  refreshTokenExpiration: 300000

# Kakao Login Properties
kakao:
  client-id: { your Client ID }
  client-secret: { your Client Secret }
  redirect-uri: { your redirect Uri }
  content-type: application/x-www-form-urlencoded;charset=utf-8
  authorization-grant-type: authorization_code
  #Get
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  user-info-uri: https://kapi.kakao.com/v2/user/me
  #Post
  token-uri: https://kauth.kakao.com/oauth/token